media: public/uploads

content:
  - name: posts
    label: Blog-Beiträge
    type: collection
    path: content/posts
    fields:
      - name: title
        label: Titel
        type: string
      - name: date
        label: Datum
        type: date
      - name: author
        label: Autor
        type: string
      - name: excerpt
        label: Auszug
        type: text
      - name: body
        label: Inhalt
        type: rich-text
